### ISSUE TITLE
ICD "Supervisory Level" Mistakenly Written to pers_supervisor_level Column

### ISSUE THREAD

**Issue by dlenz-gsa** [GSA/CHRISUpdate#122]
**Discovered By**: Terry Saunders
**Discovery Date**: April 11, 2019
**Discovery Environment**: Production
**Severity**: 2
**Description**: During HR Links updates to GCIMS, the system has been writing "Supervisory Status" from the ICD to the pers_supervisory_level; it should be written to the pers_supervisor_level column.

**Comment by tsaunders-gsa** [comment]
This has been fixed and is in production.  There were no code changes it was all database changes.
