### ISSUE TITLE
Update phone number logic change

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CHRISUpdate#132]
Update a group of phone numbers if at least one phone number remains in a group
Make no changes to a phone number group if no numbers are submitted for that group

Phone number groups
* Personal Group
  * Home Phone
  * Home Cell
  * Work Phone
  * Work Fax
  * Work Cell
  * Work Text Telephone
* Emergency Contact Group
  * Emergency Contact Home Phone
  * Emergency Contact Work Phone
  * Emergency Contact Cell Phone
  * Out Of Area Contact Home Phone
  * Out Of Area Contact Work Phone
  * Out Of Area Contact Cell Phone

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: July 31, 2019
**Test Environment**: Test
**Behavior**: Above acceptance criteria have been met.

**Comment by dlenz-gsa** [comment]
Released 8/1/2019

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: August 29, 2019
**Test Environment**: Test
