### ISSUE TITLE
Remove if statement from create hash function

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CHRISUpdate#135]
Hash is only generated on strings of length 9, remove this logic

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: August 29,, 2019
**Test Environment**: Test

**Comment by dlenz-gsa** [comment]
> Hash is only generated on strings of length 9, remove this logic

Functionally, this means that the hashed SSN (last 4) was being stored as NULL. This has been resolved.
