### ISSUE TITLE
Stop stripping + from phone numbers

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CHRISUpdate#138]

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: August 29, 2019
**Test Environment**: Test

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: September 3, 2019
**Test Environment**: Production
